### ISSUE TITLE
Segmentation fault on Windows 10 (32bit)

### ISSUE THREAD

**Issue by SaitoAtsushi** [leftmike/foment#10]
foment.exe crash immediately after starting it, reports segmentation fault.

```
$ ./foment.exe
Segmentation fault
```

On GNU debugger, I found to crash in GC.

```
$ gdb -q ./foment.exe
Reading symbols from ./foment.exe...done.
(gdb) run
Starting program: C:\msys32\home\saito\foment\windows\debug\foment.exe
[New Thread 7648.0x2058]
[New Thread 7648.0x37c]
[New Thread 7648.0x1d50]
[New Thread 7648.0xa80]

Program received signal SIGSEGV, Segmentation fault.
0x0046d624 in _FObjHdr::Generation (this=0x822c028) at ../src/foment.hpp:294
294         uint32_t Generation() {return(FlagsAndTag & OBJHDR_GEN_MASK);}
(gdb) bt 5
#0  0x0046d624 in _FObjHdr::Generation (this=0x822c028)
    at ../src/foment.hpp:294
#1  0x00407489 in ScanObject (
    pobj=0x47a2ac <PeekCharPrimitiveSymbolObject+12>) at ../src/gc.cpp:1181
#2  0x0040743d in LiveObject (pobj=0x1d56254) at ../src/gc.cpp:1172
#3  0x004077e1 in ScanObject (pobj=0x1d40160) at ../src/gc.cpp:1265
#4  0x0040743d in LiveObject (pobj=0x1d40160) at ../src/gc.cpp:1172
(More stack frames follow...)
```

It seems to invalid pointer is returned when put PrimitiveSymbolObject into AsObjHdr.

```
(gdb) p this
$1 = (_FObjHdr * const) 0x822c028
(gdb) p *this
Cannot access memory at address 0x822c028
```

**Comment by leftmike** [comment]
Fixed.
